server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://felipepedroso:z56s6t2nr9GTiBPW@veiculodatabase.ogqmtsu.mongodb.net/veiculodatabase?retryWrites=true&w=majority}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger